Add CheckCollision function
csit-sgu/mit-game-2024_2 pull request #24
Opened 2024-05-05 18:13 UTC by AnofrikovaAnna

2024-05-12 07:05 UTC, nrydanov requested changes

2024-05-12 07:05 UTC, nrydanov commented on user.cpp
> +    }
You don't really need to solve collision, it should be done if different function. You only check if collision exist and return `Vector2` object with difference from edges by each component.

Please, do not create object `Collision` here and return simple `Vector2` object.

2024-05-13 16:21 UTC, nrydanov approved these changes
LGTM

2024-05-13 18:18 UTC, mchernigin submitted a review, later dismissed

2024-05-13 18:18 UTC, mchernigin commented on user.cpp
> +        return {true, q};
Здесь не хватает поправок в вектор q: если d.x отрицателен, то значение q.x должно быть также отрицательным. Аналогично со второй координатой.

Иначе у тебя персонаж ходит сквозь стены)

P.S.: не подразумевается, что ты будешь в d хранить уже модуль разницы позиций.

2024-05-14 04:44 UTC, AnofrikovaAnna commented on user.cpp
> +        return {true, q};
В векторе d хранится разница между позициями объектов 1 и 2, что, на мой взгляд, то же самое, что и расстояние по конкретной координате между ними. И (d.x < 0) значит, что мы рассматриваем в качестве второго объекта тот, у которого координата x меньше. Если рассмотреть их в другом порядке, то есть написать (obj1.position.x - obj2.position.x), то (d.x > 0), но столкновение от этого, если оно было, не исчезнет, или, наоборот, не появится. Я что-то не правильно понимаю?

2024-05-14 08:43 UTC, vasthecat reviewed
Свяжи с этим PR соответствующую issue, чтобы она могла автоматически закрыться при мердже.

2024-05-14 08:55 UTC, vasthecat requested changes

2024-05-14 08:55 UTC, vasthecat commented on user.cpp
> +        return {true, q};
Это одно из заданий, в котором неправильно описана реализация функции. Она должна вычислять какое пересечение у объектов относительно центров друг друга, а не краёв (поэтому используются полусуммы). С помощью знаков компонент вектора q кодируется то, с какой стороны произошло столкновение. Если объект 1 был правее объекта 2, то коллизия будет отрицательной по x.

2024-05-14 08:56 UTC, vasthecat commented on user.cpp
> +        return {true, q};
Это одно из заданий, в котором неправильно описана реализация функции. Она должна вычислять какое пересечение у объектов относительно центров друг друга, а не краёв (поэтому используются полусуммы). С помощью знаков компонент вектора q кодируется то, с какой стороны произошло столкновение. Если объект 1 был правее объекта 2, то коллизия будет отрицательной по x.

2024-05-26 09:36 UTC, vasthecat approved these changes
LGTM

2024-05-28 15:55 UTC, nrydanov approved these changes
Похоже, что всё корректно.

2024-05-28 16:45 UTC, merged